# Generated by Django 6.0.1 on 2026-04-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaUploadSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_provider', models.CharField(choices=[('local', 'Local filesystem'), ('cloudinary', 'Cloudinary'), ('s3', 'Amazon S3')], default='local', max_length=32)),
                ('local_public_base_url', models.URLField(blank=True, help_text='Optional, e.g. https://cdn.example.com')),
                ('cloudinary_cloud_name', models.CharField(blank=True, max_length=255)),
                ('cloudinary_api_key', models.CharField(blank=True, max_length=255)),
                ('cloudinary_api_secret_enc', models.TextField(blank=True)),
                ('s3_bucket', models.CharField(blank=True, max_length=255)),
                ('s3_region', models.CharField(blank=True, max_length=64)),
                ('s3_prefix', models.CharField(blank=True, max_length=255)),
                ('s3_access_key_id', models.CharField(blank=True, max_length=128)),
                ('s3_secret_access_key_enc', models.TextField(blank=True)),
                ('s3_public_base_url', models.URLField(blank=True, help_text='Optional CDN or custom domain base URL')),
                ('s3_endpoint_url', models.URLField(blank=True, help_text='Optional, for MinIO / custom endpoint')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media upload settings',
            },
        ),
    ]
