# Generated by Django 6.0.1 on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("back_office", "0002_socialprovidersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialprovidersettings",
            name="instagram_app_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="socialprovidersettings",
            name="instagram_app_secret_enc",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="socialprovidersettings",
            name="instagram_auth_base_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="socialprovidersettings",
            name="instagram_graph_base_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="socialprovidersettings",
            name="instagram_scopes",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="socialprovidersettings",
            name="instagram_token_base_url",
            field=models.URLField(blank=True),
        ),
    ]
