# Generated by Django 6.0.1 on 2026-04-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0003_socialprovidersettings_instagram_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialprovidersettings',
            name='linkedin_client_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='socialprovidersettings',
            name='linkedin_client_secret_enc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialprovidersettings',
            name='linkedin_scopes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='socialprovidersettings',
            name='youtube_client_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='socialprovidersettings',
            name='youtube_client_secret_enc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='socialprovidersettings',
            name='youtube_scopes',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
