# Generated by Django 6.0.1 on 2026-04-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0005_socialprovidersettings_pinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppMailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, default='Social Man', max_length=120)),
                ('from_name', models.CharField(blank=True, max_length=120)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('reply_to_email', models.EmailField(blank=True, max_length=254)),
                ('frontend_base_url', models.URLField(blank=True, help_text='Public app URL, e.g. https://socialman.com')),
                ('password_reset_path', models.CharField(default='/reset-password', max_length=160)),
                ('send_welcome_email', models.BooleanField(default=True)),
                ('send_password_reset_email', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App mail settings',
            },
        ),
        migrations.CreateModel(
            name='AuthEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('welcome', 'Welcome email'), ('password_reset', 'Password reset email')], max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('subject', models.CharField(max_length=255)),
                ('text_body', models.TextField(blank=True)),
                ('html_body', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auth email template',
                'verbose_name_plural': 'Auth email templates',
                'ordering': ['key'],
            },
        ),
    ]
