# Generated by Django 6.0.1 on 2026-04-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0006_appmailsettings_authemailtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprovidersettings',
            name='instagram_scopes',
            field=models.CharField(blank=True, help_text='Comma-separated scopes for the standalone Instagram OAuth flow.', max_length=500),
        ),
        migrations.AlterField(
            model_name='socialprovidersettings',
            name='meta_scopes',
            field=models.CharField(blank=True, help_text='Comma-separated scopes for Facebook Page OAuth. Keep Instagram scopes in the dedicated Instagram field.', max_length=500),
        ),
    ]
