# Generated by Django 6.0.1 on 2026-04-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='storage_backend',
            field=models.CharField(default='local', max_length=32),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='storage_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='media_assets/'),
        ),
    ]
