# Generated by Django 6.0.1 on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_library", "0002_add_storage_backend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaasset",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="media_assets/"),
        ),
    ]
