# Generated by Django 6.0.1 on 2026-04-20 16:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0004_alter_socialprovider_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderDailyInsight',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_date', models.DateField()),
                ('metric_key', models.CharField(choices=[('impressions', 'Impressions'), ('reach', 'Reach'), ('engagement', 'Engagement')], max_length=32)),
                ('value', models.BigIntegerField(default=0)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_daily_insights', to='social.socialaccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('social_account', 'metric_date', 'metric_key'), name='uniq_provider_daily_insight')],
            },
        ),
        migrations.CreateModel(
            name='ProviderSyncState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_type', models.CharField(choices=[('insights', 'Insights'), ('comments', 'Comments')], max_length=32)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='idle', max_length=32)),
                ('last_error', models.TextField(blank=True)),
                ('cursor_or_checkpoint', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_sync_states', to='social.socialaccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('social_account', 'sync_type'), name='uniq_provider_sync_state')],
            },
        ),
    ]
