# Generated by Django 6.0.1 on 2026-04-13 17:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('facebook', 'Facebook')], max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(default='page', max_length=32)),
                ('external_id', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='active', max_length=32)),
                ('timezone', models.CharField(default='Asia/Saigon', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='QueueSlot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.PositiveSmallIntegerField()),
                ('local_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_slots', to='social.socialaccount')),
            ],
            options={
                'ordering': ['weekday', 'local_time', 'position'],
            },
        ),
        migrations.CreateModel(
            name='SocialConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_user_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('reauth_required', 'Reauth required')], default='pending', max_length=32)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_connections', to='accounts.workspace')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='social.socialprovider')),
            ],
            options={
                'unique_together': {('workspace', 'provider')},
            },
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='social.socialconnection'),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='social.socialprovider'),
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('provider', 'external_id', 'workspace')},
        ),
    ]
