# Generated by Django 6.0.1 on 2026-04-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialprovider',
            name='code',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('meta', 'Meta')], max_length=32, unique=True),
        ),
    ]
