# Generated by Django 6.0.1 on 2026-04-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0003_alter_socialprovider_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialprovider",
            name="code",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("meta", "Meta"),
                    ("linkedin", "LinkedIn"),
                    ("tiktok", "TikTok"),
                    ("youtube", "YouTube"),
                    ("pinterest", "Pinterest"),
                ],
                max_length=32,
                unique=True,
            ),
        ),
    ]
