# Generated by Django 6.0.1 on 2026-04-20 16:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('publishing', '0001_initial'),
        ('social', '0004_alter_socialprovider_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionThread',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thread_type', models.CharField(choices=[('comments', 'Comments')], default='comments', max_length=32)),
                ('external_object_id', models.CharField(max_length=255)),
                ('triage_status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='new', max_length=32)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_cursor', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('post_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaction_threads', to='publishing.posttarget')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_threads', to='social.socialaccount')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_threads', to='accounts.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='InteractionMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255)),
                ('parent_external_id', models.CharField(blank=True, max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('author_external_id', models.CharField(blank=True, max_length=255)),
                ('body_text', models.TextField(blank=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound')], default='inbound', max_length=32)),
                ('published_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='interactions.interactionmessage')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='interactions.interactionthread')),
            ],
            options={
                'ordering': ['published_at', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='interactionthread',
            constraint=models.UniqueConstraint(fields=('social_account', 'thread_type', 'external_object_id'), name='uniq_interaction_thread_object'),
        ),
        migrations.AddConstraint(
            model_name='interactionmessage',
            constraint=models.UniqueConstraint(fields=('thread', 'external_id'), name='uniq_interaction_message_external'),
        ),
    ]
