# Generated by Django 6.0.1 on 2026-04-13 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True)),
                ('column', models.CharField(choices=[('inbox', 'Inbox'), ('planned', 'Planned'), ('ready', 'Ready')], default='inbox', max_length=32)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='accounts.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
